"""
content_pools.py — v5 standalone sentence pools and dialogue sections.

EXTRA_POOLS    : pool name -> flat list of ready-to-use sentences
EXTRA_DIALOGUE : section name -> list of (question, answer) pairs

Both are merged into the generator's registries at import time, so every
entry here is addressable from a category defined in categories.py.
"""

from __future__ import annotations

EXTRA_POOLS: dict[str, list[str]] = {

    "animals": [
        "My dog waits by the door every afternoon.",
        "The cat sleeps on the windowsill all day.",
        "We adopted a puppy from the shelter last month.",
        "The birds start singing before the sun comes up.",
        "That dog is friendly, but he barks at strangers.",
        "Please do not feed the animals here.",
        "The kitten is still too young to leave its mother.",
        "Our chickens lay about six eggs a day.",
        "The horse is calm once it gets used to you.",
        "Careful — the dog is not used to visitors.",
        "The fish tank needs cleaning this weekend.",
        "There is a nest of birds under the roof.",
        "The carabao rests in the shade during the hottest hours.",
        "Stray cats gather behind the market at closing time.",
        "The vet said the dog needs one more vaccination.",
        "He trained the dog to sit and stay in two weeks.",
        "Wild monkeys sometimes come down from the hills.",
        "The goats wandered into the neighbour's garden again.",
        "She takes her dog for a walk every evening.",
        "The puppy chewed through the strap of my bag.",
        "Sea turtles return to the same beach every year.",
        "That bird is common here but rare further north.",
        "The farm dog barks whenever a motorcycle passes.",
        "We keep the rabbits in a shaded pen.",
        "Do not touch the stray dog without asking the owner.",
        "The parrot repeats everything my grandmother says.",
        "Insects are noisier here right after the rain.",
        "The dog recognised her voice from across the street.",
    ],

    "nature": [
        "The mountains look clearer after the rain.",
        "We walked along the river until it got dark.",
        "The sunset over the sea is worth the trip.",
        "It is cooler under the trees.",
        "The trail is muddy during the rainy season.",
        "The beach is quiet on weekday mornings.",
        "Those clouds usually mean a storm is coming.",
        "The water is shallow near the shore.",
        "Fireflies appear near the river at night.",
        "The forest smells different early in the morning.",
        "The rice fields turn golden before harvest.",
        "Strong waves make swimming dangerous today.",
        "The volcano has been quiet for many years.",
        "We planted trees along the riverbank last summer.",
        "The air is much fresher up in the highlands.",
        "The tide goes out far in the afternoon.",
        "Coral reefs take decades to recover from damage.",
        "There is a waterfall about an hour from the village.",
        "The wind picks up every afternoon around three.",
        "Wild flowers cover the hillside after the first rains.",
        "The river runs low in the dry months.",
        "It gets dark early on the eastern side of the mountain.",
        "Mangroves protect the coast from storm surges.",
        "The stars are much brighter away from the city.",
        "The soil here holds water well.",
        "Birds migrate through this valley twice a year.",
        "The heat is bearable once the sea breeze starts.",
        "Erosion has narrowed the beach considerably.",
    ],

    "people": [
        "She is the kindest person I know.",
        "He is tall and always wears a cap.",
        "My grandmother is small but very strong-willed.",
        "He talks quietly, so you have to listen carefully.",
        "She has a great sense of humour.",
        "My brother is the serious one in the family.",
        "The woman at the counter was very helpful.",
        "He is shy at first, but he warms up quickly.",
        "She never raises her voice, even when she is upset.",
        "My friend is the type who remembers every birthday.",
        "He looks strict, but he is actually very gentle.",
        "She works hard and rarely complains.",
        "That man has lived in this town his whole life.",
        "My cousin looks exactly like her mother.",
        "He is patient with children.",
        "She has a way of making everyone feel welcome.",
        "My neighbour is curious about everything.",
        "He is honest, sometimes uncomfortably so.",
        "She is the youngest of five siblings.",
        "He wears glasses and always carries a notebook.",
        "My teacher was strict but genuinely fair.",
        "She speaks three languages fluently.",
        "He is the kind of person who fixes things without being asked.",
        "My father does not say much, but he notices everything.",
        "She is confident without being loud about it.",
        "He has an easy laugh that puts people at ease.",
        "My aunt is generous to a fault.",
        "People trust her because she keeps her word.",
    ],

    "home_life": [
        "I will wash the dishes after dinner.",
        "Please close the window before you leave.",
        "The laundry is still hanging outside.",
        "We clean the whole house every Saturday.",
        "The rice is almost ready.",
        "Someone left the light on in the bathroom.",
        "Can you help me move this table?",
        "The faucet has been leaking for a week.",
        "I forgot to buy soap again.",
        "Take off your shoes at the door, please.",
        "The electricity went out for two hours last night.",
        "We keep the extra blankets in the cabinet.",
        "Dinner is at seven, so do not be late.",
        "The trash is collected every Tuesday morning.",
        "I need to water the plants before it gets hot.",
        "My room is small but I like it that way.",
        "The washing machine is making a strange noise.",
        "Let us cook something simple tonight.",
        "Please do not leave the gate unlocked.",
        "The refrigerator needs defrosting.",
        "We repainted the living room last summer.",
        "The kids' toys are all over the floor again.",
        "I sweep the front of the house every morning.",
        "There is no more drinking water in the container.",
        "The fan works better than the air conditioner in this room.",
        "We split the bills evenly every month.",
        "I finally cleaned out the storage room.",
        "The neighbours are renovating, so it is noisy all day.",
    ],

    "clothing": [
        "This shirt is too tight around the shoulders.",
        "Do you have this in another colour?",
        "I need something formal for the interview.",
        "These shoes are comfortable for walking all day.",
        "The dress fits perfectly.",
        "It is too hot for long sleeves today.",
        "I am looking for a light jacket.",
        "This fabric wrinkles very easily.",
        "The uniform has to be washed by Monday.",
        "That colour really suits you.",
        "I bought these jeans on sale.",
        "Bring an umbrella and a light coat.",
        "The tailor can shorten the sleeves by Friday.",
        "My shoes got soaked in the rain.",
        "She wore a simple dress to the ceremony.",
        "This sweater shrank in the wash.",
        "I prefer cotton in this kind of weather.",
        "The zipper on my bag is broken.",
        "He always dresses neatly, even at home.",
        "Do I need to wear something formal?",
        "These sandals are not good for long walks.",
        "The store exchanges items within seven days.",
        "I have nothing clean to wear tomorrow.",
        "Her outfit was elegant but very simple.",
        "Please iron my shirt for tomorrow.",
        "The traditional fabric is woven entirely by hand.",
    ],

    "jobs": [
        "I start work at eight in the morning.",
        "She works the night shift three times a week.",
        "He just got promoted to team leader.",
        "The interview lasted about thirty minutes.",
        "I am looking for a part-time job.",
        "They are hiring, but only for experienced applicants.",
        "My contract ends in December.",
        "He resigned after five years with the company.",
        "The pay is decent, but the commute is long.",
        "I have a meeting at ten and another at two.",
        "She works from home twice a week.",
        "The training lasts two weeks before you start.",
        "Please bring your résumé and a valid ID.",
        "He works two jobs to support his family.",
        "The office is closed on public holidays.",
        "I asked my supervisor for a day off.",
        "New employees are on probation for six months.",
        "The team meets every Monday morning.",
        "She is very good at handling difficult customers.",
        "Overtime is paid at a higher rate.",
        "I sent my application last week but have not heard back.",
        "He decided to go freelance instead.",
        "The company offers health insurance after one year.",
        "My schedule changes every week.",
        "She is the most reliable person on the team.",
        "They asked me to start as soon as possible.",
    ],

    "celebrations": [
        "Happy birthday! I hope you have a wonderful year ahead.",
        "The wedding is on the twelfth of next month.",
        "We are having a small party at home.",
        "Congratulations on your graduation!",
        "The whole family gathers every Christmas.",
        "Thank you for inviting me to the celebration.",
        "The fiesta lasts for three days.",
        "Please come, and feel free to bring someone with you.",
        "We prepared enough food for thirty people.",
        "The ceremony starts at four in the afternoon.",
        "Do not forget to bring a gift.",
        "It was a simple celebration, but a happy one.",
        "The children were the most excited of all.",
        "We booked the venue six months in advance.",
        "Everyone wore matching colours for the reunion.",
        "The neighbours joined us for the New Year countdown.",
        "There will be music and dancing after dinner.",
        "Happy anniversary to both of you.",
        "We celebrate this holiday every year without fail.",
        "The town holds a parade to honour its patron saint.",
        "She blew out the candles and made a wish.",
        "Relatives abroad joined the celebration over video call.",
        "The house was decorated with lights and flowers.",
        "We took a family photo before everyone left.",
        "Best wishes to the newlyweds.",
        "The programme ended with a speech from the eldest uncle.",
    ],

    "city_places": [
        "The market is two blocks from here.",
        "Is there a pharmacy nearby?",
        "The mall opens at ten on weekdays.",
        "The bank is closed for the holiday.",
        "There is a small café across the street.",
        "The hospital is about fifteen minutes away by car.",
        "The church is the oldest building in town.",
        "The bus terminal is always crowded on Fridays.",
        "You can withdraw cash at the convenience store.",
        "The park gets busy in the early evening.",
        "The library is quiet in the mornings.",
        "There is a public restroom on the second floor.",
        "The road is under repair, so expect delays.",
        "The night market runs until midnight.",
        "Parking is free for the first two hours.",
        "The barangay hall handles that kind of request.",
        "This neighbourhood is safe but poorly lit at night.",
        "A new supermarket opened near the school.",
        "The post office is beside the municipal building.",
        "Traffic here is worst between five and seven.",
        "The clinic accepts walk-ins in the morning only.",
        "There is a jeepney stop just around the corner.",
        "Rent has gone up a lot in this area.",
        "The plaza is where everyone gathers on weekends.",
        "The nearest gas station is on the highway.",
        "That building used to be a cinema.",
    ],

    "gardening_farming": [
        "The tomatoes are almost ready to pick.",
        "Water the plants before the sun gets strong.",
        "The soil here is good for root crops.",
        "We planted rice at the start of the rainy season.",
        "These leaves are turning yellow from too much water.",
        "The mango tree bears fruit once a year.",
        "He sells vegetables at the market every Sunday.",
        "The harvest was smaller than last year.",
        "Compost works better than chemical fertiliser here.",
        "The seedlings need shade for the first week.",
        "We lost half the crop to the typhoon.",
        "The chickens are fed twice a day.",
        "Prune the branches after the fruiting season.",
        "The irrigation canal has been dry for weeks.",
        "Herbs grow well in pots by the window.",
        "We rotate the crops to keep the soil healthy.",
        "The farmers start work before sunrise.",
        "Rain came late this year, so planting was delayed.",
        "These seeds germinate in about five days.",
        "The garden takes work, but it feeds the whole family.",
        "Insects damaged the young leaves overnight.",
        "The corn is taller than I am now.",
        "We store the rice in sacks in the back room.",
        "He learned farming from his grandfather.",
        "The price of fertiliser keeps rising.",
    ],

    "fitness": [
        "I run three times a week before work.",
        "Stretch properly before you start.",
        "My legs are sore from yesterday's workout.",
        "Walking is enough exercise if you do it daily.",
        "The gym is cheaper if you pay for a whole year.",
        "Drink water throughout the session.",
        "He lifts weights every other day.",
        "Start slowly and build up over time.",
        "I joined a running group last month.",
        "Rest days are just as important as training days.",
        "She swims for an hour every morning.",
        "My knee still hurts when I climb stairs.",
        "Do not skip the warm-up.",
        "The class is suitable for complete beginners.",
        "I feel much better since I started exercising.",
        "He trains for the marathon on weekends.",
        "Proper form matters more than heavy weights.",
        "We play basketball at the covered court every Sunday.",
        "Sleep affects recovery more than most people realise.",
        "The trainer adjusted my routine after the injury.",
        "Twenty minutes a day is a realistic place to start.",
        "Stretching helps with the stiffness in my back.",
        "She cycles to work instead of driving.",
        "Consistency beats intensity in the long run.",
    ],

    "culture": [
        "My grandmother taught me this song when I was little.",
        "We still speak our first language at home.",
        "This dish is served only during the fiesta.",
        "The dance tells the story of the harvest.",
        "Older people here still follow the old customs.",
        "The pattern on this cloth has a specific meaning.",
        "Young people are learning the traditional crafts again.",
        "The ceremony has been performed for generations.",
        "Elders are greeted with a gesture of respect.",
        "This recipe was never written down.",
        "The festival brings everyone back to the hometown.",
        "The language has many words with no direct translation.",
        "Guests are always offered food, even unannounced ones.",
        "The songs were passed down orally.",
        "Weaving takes months for a single piece.",
        "Certain customs are followed strictly at weddings.",
        "The town celebrates its founding every January.",
        "Traditions change, but the meaning behind them survives.",
        "Storytelling was how history was preserved here.",
        "The dialect differs from one town to the next.",
        "Respect for elders is taught very early.",
        "The instruments are made from local materials.",
        "Every region has its own version of this dish.",
        "The community decides together how the ritual is done.",
    ],

    "kids": [
        "The baby finally fell asleep.",
        "He is learning to walk.",
        "She started school this year.",
        "The children are playing outside.",
        "Do not run near the stairs.",
        "He refuses to eat vegetables.",
        "Please wash your hands before eating.",
        "She can already count to twenty.",
        "The toddler cries whenever we leave the room.",
        "Bedtime is at eight on school nights.",
        "He shares his toys without being told.",
        "They fight over the same toy every day.",
        "She drew a picture of the whole family.",
        "The baby is teething, so she has been fussy.",
        "He asks questions about everything.",
        "Read him one story and then lights out.",
        "The kids get restless when it rains all day.",
        "She was shy on her first day of class.",
        "He fell off the swing but he is fine.",
        "Screen time is limited to one hour a day.",
        "They learn faster than we expect.",
        "The little one follows her brother everywhere.",
        "Praise works better than scolding at this age.",
        "He is proud of tying his own shoes.",
    ],

    "school_life": [
        "Class starts at seven thirty sharp.",
        "I forgot my notebook at home.",
        "The exam covers the first three chapters.",
        "Can I borrow your pen for a moment?",
        "We have a group project due next week.",
        "The teacher explained it again after class.",
        "I studied until midnight for this test.",
        "Please submit your assignment before Friday.",
        "The library is open until six.",
        "He always sits in the front row.",
        "We have a substitute teacher today.",
        "The lesson was difficult but interesting.",
        "Enrolment starts in the first week of June.",
        "She got the highest score in the class.",
        "There is no class tomorrow because of the holiday.",
        "I need to review my notes before the quiz.",
        "The school bus leaves at exactly six thirty.",
        "Our teacher gives extra points for participation.",
        "We are practising for the school programme.",
        "The tuition fee can be paid in instalments.",
        "I did not understand the last part of the lesson.",
        "The results will be posted next Monday.",
        "He transferred from another school last year.",
        "Group study helps more than reading alone.",
    ],

    "basics_everyday": [
        "What time is it?",
        "I am hungry.",
        "This is my bag.",
        "The store is open.",
        "I do not understand.",
        "Please wait a moment.",
        "It is very hot today.",
        "Where are you going?",
        "I am almost there.",
        "That is too expensive.",
        "I will be back later.",
        "Let us go together.",
        "I am tired.",
        "This one is better.",
        "Come here, please.",
        "I forgot my phone.",
        "It is not far from here.",
        "Give me five minutes.",
        "I am ready.",
        "Do not worry about it.",
        "It is raining outside.",
        "I need to go now.",
        "Can you say that again?",
        "That sounds good to me.",
        "I will call you tonight.",
        "See you tomorrow.",
        "It is up to you.",
        "I am not sure yet.",
    ],
}


EXTRA_DIALOGUE: dict[str, list[tuple[str, str]]] = {

    "animals": [
        ("Do you have any pets?", "Yes, two dogs and a very opinionated cat."),
        ("Is your dog friendly?", "He is, but give him a minute to sniff you first."),
        ("Can I pet him?", "Of course, just let him come to you."),
        ("What breed is she?", "She is a mix — we adopted her from a shelter."),
        ("How often do you feed them?", "Twice a day, morning and early evening."),
        ("Does the cat go outside?", "Only in the yard, and never at night."),
        ("Is it safe to approach that stray?", "Better not. Feed it from a distance if you want to help."),
        ("Where did you get the puppy?", "From a neighbour whose dog had a litter."),
        ("Do the birds come every day?", "Every morning, right after we put out the seed."),
        ("What do you do when they get sick?", "There is a vet two streets away who is very good."),
        ("Why is the dog barking so much?", "He does that whenever a motorcycle passes."),
        ("Are those chickens yours?", "Yes, they give us about six eggs a day."),
    ],

    "nature": [
        ("Is the beach far from here?", "About twenty minutes by tricycle."),
        ("What is the best time to visit the falls?", "Early morning, before the crowd arrives."),
        ("Can we swim in the river?", "Yes, but stay near the shallow side."),
        ("Does it rain much this month?", "Almost every afternoon, usually for an hour."),
        ("Is the trail hard?", "It is steep in parts, but nothing dangerous."),
        ("What is that mountain called?", "The locals just call it the sleeping giant."),
        ("Are there mosquitoes at night?", "Plenty near the water, so bring repellent."),
        ("Is the water safe to drink?", "Not from the stream — we boil it first."),
        ("When does the sun set here?", "Around six, a bit earlier behind the ridge."),
        ("Has the forest changed much?", "Yes, but the replanting has helped in the last decade."),
        ("Why are the fields flooded?", "That is normal for rice at this stage."),
        ("Is it cold up there?", "Cool at night, so bring a jacket."),
    ],

    "people_relationships": [
        ("How long have you two known each other?", "Since primary school, so almost twenty years."),
        ("What is your friend like?", "Quiet at first, but very funny once he relaxes."),
        ("Is that your brother?", "Yes, the tall one with the cap."),
        ("Do you get along with your neighbours?", "Very well — they watch the house when we travel."),
        ("Have you met her family?", "Only her parents, and they were very welcoming."),
        ("Do you still talk to your old classmates?", "A few of them, mostly in a group chat."),
        ("Who do you go to when something is wrong?", "My older sister, without a doubt."),
        ("Are you close to your cousins?", "We grew up together, so yes, very close."),
        ("Did you two argue?", "We did, but we sorted it out the same evening."),
        ("How do you keep in touch?", "We video call every Sunday, no matter what."),
        ("Is he always this quiet?", "Around new people, yes. He opens up quickly though."),
        ("Would you introduce me?", "Of course, come with me now."),
    ],

    "home_life": [
        ("Whose turn is it to cook?", "Mine, but I would happily trade."),
        ("Where do we keep the extra towels?", "Second shelf in the cabinet, on the left."),
        ("Did you lock the gate?", "Yes, and I closed the windows too."),
        ("Can you help me move this?", "Sure — let me take the heavier side."),
        ("What time is dinner?", "Around seven, once the rice is done."),
        ("Is the laundry dry?", "Almost. Give it another hour in this sun."),
        ("The faucet is leaking again.", "I will call someone tomorrow morning."),
        ("Do we have soap left?", "None. Add it to the list before you go."),
        ("Who left the light on?", "Probably me. Sorry, I will be more careful."),
        ("Can I stay over tonight?", "Of course, the spare room is already made up."),
        ("Should we clean today or tomorrow?", "Today, so the weekend stays free."),
        ("How much is the electricity bill this month?", "Higher than usual — the heat is not helping."),
    ],

    "jobs_careers": [
        ("What do you do for a living?", "I work as a nurse at the district hospital."),
        ("Are they still hiring?", "Yes, applications close at the end of the month."),
        ("What time do you start?", "Eight, but I usually arrive fifteen minutes early."),
        ("How was the interview?", "Shorter than I expected, and quite friendly."),
        ("Do you enjoy the work?", "Most days, yes. The schedule is the hard part."),
        ("What qualifications do I need?", "A relevant degree and at least one year of experience."),
        ("Is there room to grow here?", "There is, especially if you are willing to train others."),
        ("When will I hear back?", "Within a week, either way."),
        ("Why did you leave your last job?", "I wanted work that used more of my training."),
        ("Do you work weekends?", "Only one Saturday a month."),
        ("Can I ask about the salary range?", "Of course — it depends on experience, but I can give you a bracket."),
        ("Is the job permanent?", "It starts as a contract, with review after six months."),
    ],

    "celebrations": [
        ("When is the party?", "Saturday evening, starting around six."),
        ("Can I bring something?", "Just yourself, but dessert is always welcome."),
        ("What are we celebrating?", "My grandmother's eightieth birthday."),
        ("Is there a dress code?", "Smart casual is fine, nothing formal."),
        ("How many guests are coming?", "About forty, mostly family."),
        ("Where will the wedding be held?", "At the old church, with the reception nearby."),
        ("Do I need to confirm?", "Please do, so we can finalise the food count."),
        ("What gift is appropriate?", "Something small and practical is perfectly fine."),
        ("What time does the programme start?", "Right after dinner, around eight."),
        ("Will there be food for the kids?", "Yes, we ordered a separate menu for them."),
        ("Can my sister come along?", "Absolutely, the more the better."),
        ("How long does the fiesta last?", "Three days, but the main day is Sunday."),
    ],

    "clothing": [
        ("Do you have this in a larger size?", "Let me check the stockroom for you."),
        ("Can I try this on?", "Of course, the fitting room is just there."),
        ("How much is this?", "It is four hundred, or three fifty if you take two."),
        ("Does this colour suit me?", "It does, though the blue might suit you even better."),
        ("Can this be altered?", "Yes, and it should be ready by Friday."),
        ("What should I wear to the interview?", "Something plain and neat — a collared shirt is enough."),
        ("Is this washable by machine?", "Better by hand, or it will lose its shape."),
        ("Do you accept exchanges?", "Within seven days, with the receipt."),
        ("Is this too warm for the season?", "A little. Try the cotton one instead."),
        ("Where can I buy shoes nearby?", "There are two shops at the end of this row."),
        ("Are these on sale?", "Everything on that rack is twenty percent off."),
        ("How long will the tailoring take?", "Two fittings, so about a week."),
    ],

    "gardening_farming": [
        ("When should I plant these?", "Right at the start of the rains."),
        ("How often do I water them?", "Once daily, early morning is best."),
        ("Why are the leaves yellow?", "Usually too much water, or not enough sun."),
        ("Where can I buy seeds?", "At the agricultural supply store near the market."),
        ("Is this fruit ready?", "Give it a few more days — it is still firm."),
        ("Do you use fertiliser?", "Mostly compost. It is cheaper and works well here."),
        ("How was the harvest?", "Smaller than last year, but the price is better."),
        ("Can I grow this in a pot?", "Yes, as long as it gets morning sunlight."),
        ("What eats the young leaves?", "Insects, mostly at night. Check under the leaves."),
        ("How long until it grows?", "About three months from planting to harvest."),
        ("Do you sell at the market?", "Every Sunday, from very early until noon."),
        ("Is the soil good here?", "Good for root crops, less so for rice."),
    ],

    "fitness": [
        ("How often do you exercise?", "Three times a week, usually before work."),
        ("Is this safe for beginners?", "Yes, just start with lighter weight and good form."),
        ("Do I need to warm up?", "Always — five to ten minutes is enough."),
        ("How much is the monthly fee?", "Six hundred, or cheaper if you pay yearly."),
        ("Is walking enough?", "For general health, thirty minutes daily is a solid start."),
        ("How long should I rest between sets?", "About a minute for most exercises."),
        ("Is it normal to be this sore?", "For the first week, yes. It settles down."),
        ("What should I eat before running?", "Something light, about an hour before."),
        ("Can I train with a knee injury?", "Not without clearing it with a physiotherapist first."),
        ("Do you want to join us tomorrow?", "Yes, what time do you start?"),
        ("How many rest days do I need?", "At least two, spread through the week."),
        ("Am I doing this correctly?", "Almost — keep your back straight and slow it down."),
    ],

    "culture_traditions": [
        ("What is this festival for?", "It honours the town's patron saint."),
        ("Who taught you this song?", "My grandmother, when I was about six."),
        ("Do you still speak the dialect at home?", "Yes, though the children mix it with English."),
        ("Is this a traditional dish?", "It is, and every family makes it slightly differently."),
        ("What does this pattern mean?", "Each line represents a river in the region."),
        ("How old is the tradition?", "Older than anyone can remember precisely."),
        ("Are young people still learning it?", "More than before, actually — there is a revival."),
        ("How should I greet the elders?", "Take their hand and touch it lightly to your forehead."),
        ("Is it rude to refuse food?", "A little. Accept a small amount if you can."),
        ("Can visitors join the ceremony?", "Yes, and people will be glad you asked first."),
        ("Why is it done this way?", "That is how it was passed down, and the meaning matters more than the reason."),
        ("Is there a written record?", "Very little. Most of it lives in memory and practice."),
    ],

    "kids_parenting": [
        ("How old is she?", "She turns three next month."),
        ("Is he sleeping through the night?", "Not yet, but we are getting closer."),
        ("What time do the kids go to bed?", "Eight on school nights, a bit later on weekends."),
        ("Can he eat this?", "Better not — he is still avoiding anything with nuts."),
        ("Does she go to school already?", "She started kindergarten this year."),
        ("How do you handle tantrums?", "Stay calm, wait it out, and talk afterwards."),
        ("Is it normal to be this picky?", "Very normal at that age. It usually passes."),
        ("How much screen time do you allow?", "About an hour, and never right before bed."),
        ("Do you need help with the bags?", "Yes, please — I have my hands full."),
        ("What do you do when they fight?", "Separate them first, then let each one explain."),
        ("Is he shy around strangers?", "Only for the first few minutes."),
        ("Should I be worried about the speech delay?", "Mention it at the next check-up, just to be sure."),
    ],

    "school_life": [
        ("What page are we on?", "Page fifty-three, second paragraph."),
        ("Did we have homework?", "Yes, exercises one to ten."),
        ("Can I borrow a pen?", "Here, keep it. I have another."),
        ("When is the deadline?", "Friday before class, no extensions."),
        ("Will this be on the exam?", "Most likely, so review it carefully."),
        ("Can we work in pairs?", "Yes, but both of you must contribute."),
        ("I do not understand this part.", "Come after class and we will go through it slowly."),
        ("Is the library open now?", "Until six on weekdays."),
        ("How long should the essay be?", "Around eight hundred words."),
        ("Do we need to bring a calculator?", "Yes, and your own graphing paper."),
        ("When will we get our results?", "They should be posted by Monday."),
        ("Can I make up the missed quiz?", "Yes, see me during the lunch break."),
    ],
}
