"""
content_domains.py — v5 domain packs.

Each domain follows the same schema used by generator.DOMAINS:
    subjects, verbs_{b,i,a}, objects_{b,i,a}, extras_{b,i,a}, questions_{b,i,a}
where b/i/a = beginner / intermediate / advanced.

These are merged into generator.DOMAINS at import time.
"""

from __future__ import annotations

EXTRA_DOMAINS: dict[str, dict] = {

    # ────────────────────────────────────────────────────────────────────
    "animals": {
        "subjects": [
            "The dog", "Our cat", "The farmer's horse", "A flock of birds",
            "The stray puppy", "My neighbour's parrot", "The zookeeper",
            "A herd of goats", "The veterinarian", "The old water buffalo",
            "A family of ducks", "The rescue kitten", "The village carabao",
            "A curious monkey", "The fisherman's dog",
        ],
        "verbs_b": ["chased", "fed", "watched", "found", "followed",
                    "played with", "cleaned", "carried"],
        "verbs_i": ["adopted", "trained", "examined", "rescued", "protected",
                    "released", "groomed", "observed"],
        "verbs_a": ["rehabilitated", "documented", "monitored", "reintroduced",
                    "catalogued", "acclimatised"],
        "objects_b": ["the ball", "its food", "the puppy", "the water bowl",
                      "a stick", "the baby chicks", "the cage"],
        "objects_i": ["the injured bird", "the stray litter", "the nesting site",
                      "the feeding schedule", "the animal shelter",
                      "the migrating flock"],
        "objects_a": ["the endangered species population",
                      "the wildlife corridor survey",
                      "the captive breeding programme",
                      "the behavioural enrichment plan"],
        "extras_b": ["in the yard.", "every morning.", "before sunset.",
                     "very gently.", "near the fence.", "with great excitement."],
        "extras_i": ["under the vet's supervision.",
                     "following strict safety guidelines.",
                     "with the help of local volunteers.", "over several weeks.",
                     "without disturbing the nest."],
        "extras_a": ["in line with international conservation standards.",
                     "using non-invasive tracking methods.",
                     "as part of a long-term ecological study.",
                     "with measurable improvements in survival rates."],
        "questions_b": [
            "Do you have any pets at home?",
            "What is your dog's name?",
            "Is this animal friendly?",
            "How often do you feed your cat?",
            "Can I pet the puppy?",
            "Where does that bird live?",
        ],
        "questions_i": [
            "What should I feed a rescued kitten?",
            "How do you train a dog not to jump on visitors?",
            "Which animals are common in this area?",
            "Is it safe to approach a stray dog?",
            "How far do these birds usually migrate?",
        ],
        "questions_a": [
            "What ecological role does this predator play in the local food web?",
            "How effective are captive breeding programmes for endangered species?",
            "Which behavioural indicators suggest chronic stress in captive animals?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "nature": {
        "subjects": [
            "The river", "The forest", "A mountain trail", "The morning mist",
            "The coral reef", "Our local park", "The volcano", "The rice terraces",
            "A quiet beach", "The rainy season", "The mangrove swamp",
            "The old acacia tree", "The waterfall", "The coastline",
        ],
        "verbs_b": ["covered", "reached", "surrounded", "filled", "crossed",
                    "shaded", "touched", "hid"],
        "verbs_i": ["transformed", "sheltered", "sustained", "eroded",
                    "regenerated", "attracted", "shaped", "nourished"],
        "verbs_a": ["stabilised", "sequestered", "buffered", "recolonised",
                    "regulated", "replenished"],
        "objects_b": ["the whole valley", "the small village", "the path",
                      "the fields", "the sand", "the old bridge", "the hills"],
        "objects_i": ["the surrounding wetlands", "the nesting grounds",
                      "the fragile topsoil", "the water supply",
                      "the seasonal migration route", "the shoreline"],
        "objects_a": ["the entire watershed ecosystem",
                      "the carbon storage capacity of the region",
                      "the biodiversity of the coastal shelf",
                      "the microclimate of the upland forest"],
        "extras_b": ["after the rain.", "at sunrise.", "for many years.",
                     "in the dry season.", "all year round.", "in the afternoon."],
        "extras_i": ["long before the settlement was built.",
                     "despite years of heavy logging.",
                     "thanks to community reforestation efforts.",
                     "during the strongest storms.",
                     "as the seasons changed."],
        "extras_a": ["according to decades of satellite observation.",
                     "at a rate consistent with regional climate models.",
                     "with significant implications for downstream communities.",
                     "in ways that traditional land management already anticipated."],
        "questions_b": [
            "Is the beach far from here?",
            "What is the name of that mountain?",
            "Does it rain a lot in this season?",
            "Can we swim in this river?",
            "Where can I see the sunset?",
            "Is this trail difficult for beginners?",
        ],
        "questions_i": [
            "What is the best month to visit the falls?",
            "Are there any protected areas nearby?",
            "How has the coastline changed in the last ten years?",
            "Why is this forest important to the local community?",
            "What kind of trees grow in this region?",
        ],
        "questions_a": [
            "How does mangrove loss affect storm surge resilience along this coast?",
            "What role does this watershed play in regional groundwater recharge?",
            "How do reforestation efforts compare with natural regeneration here?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "people_description": {
        "subjects": [
            "My older brother", "The woman at the counter", "Our neighbour",
            "The tall man in the blue shirt", "A quiet student",
            "My best friend", "The elderly gentleman", "That cheerful nurse",
            "The little girl next door", "My cousin from the province",
            "The man with the grey beard", "A young couple",
        ],
        "verbs_b": ["looks", "seems", "sounds", "acts", "smiles", "speaks",
                    "walks", "dresses"],
        "verbs_i": ["carries himself", "comes across as", "reminds me of",
                    "strikes people as", "presents himself as", "behaves like",
                    "treats everyone as", "handles things like"],
        "verbs_a": ["projects an air of", "embodies", "conveys",
                    "radiates", "cultivates an impression of",
                    "carries the quiet confidence of"],
        "objects_b": ["very kind", "quite tall", "a bit shy", "really funny",
                      "very patient", "always tired", "extremely polite"],
        "objects_i": ["someone you can rely on", "a naturally curious person",
                      "a person of few words", "the calmest one in the room",
                      "the sort who never complains", "a genuinely warm host"],
        "objects_a": ["a person of considerable integrity",
                      "an unusually perceptive listener",
                      "someone shaped by a lifetime of responsibility",
                      "a quietly formidable presence"],
        "extras_b": ["to everyone.", "most of the time.", "when you first meet him.",
                     "even on busy days.", "in front of strangers.", "at family gatherings."],
        "extras_i": ["once you get to know her better.",
                     "especially when the pressure is on.",
                     "despite everything he has been through.",
                     "without ever asking for recognition.",
                     "in a way that puts people at ease."],
        "extras_a": ["without any apparent effort at self-presentation.",
                     "in a manner that invites trust rather than demanding it.",
                     "shaped by years of quiet, unglamorous service.",
                     "in ways that only become obvious over time."],
        "questions_b": [
            "What does your brother look like?",
            "How old is she?",
            "Is he your friend?",
            "Who is that man over there?",
            "What is your friend like?",
            "Do I know her from somewhere?",
        ],
        "questions_i": [
            "How would you describe your closest friend?",
            "What kind of person do you get along with best?",
            "Has she always been this outgoing?",
            "What first impression do you think you give people?",
            "Who has influenced you the most in your life?",
        ],
        "questions_a": [
            "To what extent does temperament shape the way people are perceived?",
            "How much of a person's character is visible in a first encounter?",
            "Why do we form such durable judgements from such limited evidence?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "relationships": {
        "subjects": [
            "My best friend", "The newly married couple", "Our group of friends",
            "My classmate", "The two brothers", "A long-distance couple",
            "My childhood friend", "The whole barkada", "Her fiancé",
            "The neighbours across the street", "My workmate",
        ],
        "verbs_b": ["called", "visited", "helped", "missed", "invited",
                    "thanked", "forgave", "hugged"],
        "verbs_i": ["reconnected with", "supported", "reassured", "confided in",
                    "made peace with", "encouraged", "stood by", "checked on"],
        "verbs_a": ["reconciled with", "renegotiated boundaries with",
                    "reaffirmed their commitment to", "worked through old tensions with",
                    "rebuilt trust with"],
        "objects_b": ["each other", "the whole family", "her sister",
                      "an old classmate", "the new neighbour", "his cousin",
                      "the group"],
        "objects_i": ["a friend going through a hard time",
                      "someone they had not spoken to in years",
                      "a relative living overseas", "a struggling colleague",
                      "the friend who moved away", "a grieving neighbour"],
        "objects_a": ["a relationship strained by years of silence",
                      "a friendship complicated by distance and circumstance",
                      "the family member everyone had quietly given up on",
                      "a partnership tested by long separation"],
        "extras_b": ["every weekend.", "after a long time.", "with a warm smile.",
                     "without hesitation.", "over dinner.", "at the reunion."],
        "extras_i": ["even though the timing was difficult.",
                     "after several months of awkward silence.",
                     "in a way that felt genuinely honest.",
                     "before things could get any worse.",
                     "with patience neither of them expected."],
        "extras_a": ["in a conversation that had been postponed for years.",
                     "with the kind of honesty that only long history allows.",
                     "recognising that neither side was entirely blameless.",
                     "and found the relationship stronger for it."],
        "questions_b": [
            "How long have you two known each other?",
            "Is he your best friend?",
            "Do you miss your old friends?",
            "Are you free to hang out this weekend?",
            "Who did you go with?",
            "Can I bring a friend along?",
        ],
        "questions_i": [
            "How do you keep in touch with friends who live far away?",
            "What makes a friendship last for decades?",
            "Have you ever had to apologise to someone you love?",
            "How do you handle disagreements with close friends?",
            "Do you think people change after they get married?",
        ],
        "questions_a": [
            "How do long-term relationships survive fundamental disagreement?",
            "What obligations do we owe friends we have grown apart from?",
            "Is forgiveness a decision, a process, or something we simply arrive at?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "home_life": {
        "subjects": [
            "My mother", "The whole household", "My roommate", "The landlord",
            "Our helper", "The kids", "My father", "The family",
            "The person upstairs", "Everyone at home", "My younger sister",
        ],
        "verbs_b": ["washed", "cooked", "cleaned", "fixed", "swept", "folded",
                    "locked", "watered"],
        "verbs_i": ["rearranged", "repaired", "organised", "repainted",
                    "decluttered", "scheduled", "replaced", "childproofed"],
        "verbs_a": ["systematically reorganised", "retrofitted", "budgeted for",
                    "renovated", "streamlined the upkeep of", "future-proofed"],
        "objects_b": ["the dishes", "the laundry", "the floor", "the windows",
                      "the plants", "the kitchen", "the gate"],
        "objects_i": ["the storage room", "the leaking faucet",
                      "the weekly chore rota", "the old furniture",
                      "the electricity bill", "the spare bedroom"],
        "objects_a": ["the household's entire maintenance schedule",
                      "the ageing electrical wiring",
                      "the long-postponed roof repairs",
                      "the family's shared monthly budget"],
        "extras_b": ["before dinner.", "every Saturday.", "in the morning.",
                     "without being asked.", "after the rain.", "in ten minutes."],
        "extras_i": ["while everyone else was still asleep.",
                     "using whatever was already in the house.",
                     "to make the small space feel bigger.",
                     "before the visitors arrived.",
                     "after weeks of putting it off."],
        "extras_a": ["with an eye on both cost and long-term durability.",
                     "in a way that finally suited how the family actually lives.",
                     "balancing everyone's competing preferences.",
                     "without disrupting anyone's daily routine."],
        "questions_b": [
            "Whose turn is it to wash the dishes?",
            "Where do we keep the extra towels?",
            "Did you lock the door?",
            "Can you help me carry this?",
            "What time do we eat dinner?",
            "Is the laundry dry yet?",
        ],
        "questions_i": [
            "How do you divide the chores in your house?",
            "What is the fastest way to get this stain out?",
            "Should we call someone to fix the leak or try it ourselves?",
            "How much do you usually spend on groceries each month?",
            "Where is the best place to store this so it does not spoil?",
        ],
        "questions_a": [
            "How do households negotiate unpaid domestic labour fairly?",
            "What makes a small living space feel genuinely comfortable?",
            "Is it more economical to repair old appliances or replace them outright?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "clothing_fashion": {
        "subjects": [
            "The tailor", "My sister", "The shop assistant", "A local designer",
            "The customer", "My cousin", "The seamstress", "The model",
            "That boutique", "The uniform supplier",
        ],
        "verbs_b": ["wore", "bought", "tried on", "washed", "ironed", "returned",
                    "borrowed", "folded"],
        "verbs_i": ["altered", "matched", "recommended", "restyled", "measured",
                    "packed", "mended", "coordinated"],
        "verbs_a": ["tailored", "curated", "repurposed", "hand-finished",
                    "sustainably sourced", "reconstructed"],
        "objects_b": ["a blue shirt", "the new shoes", "her dress", "a warm jacket",
                      "the school uniform", "a pair of jeans", "the old sweater"],
        "objects_i": ["the outfit for the interview", "a hand-me-down blazer",
                      "the wedding entourage attire", "the fabric she chose",
                      "an outfit for the rainy season", "the graduation gown"],
        "objects_a": ["a capsule wardrobe built around neutral tones",
                      "a hand-woven textile with regional significance",
                      "a made-to-measure suit with working buttonholes",
                      "an upcycled collection from surplus fabric"],
        "extras_b": ["for the party.", "at a good price.", "in the right size.",
                     "before the trip.", "just this once.", "in a hurry."],
        "extras_i": ["without spending too much money.",
                     "so it would suit the occasion.",
                     "after two rounds of fittings.",
                     "to make it last another season.",
                     "based on what the weather would be like."],
        "extras_a": ["with attention to drape, weight, and seasonal wear.",
                     "honouring the traditional weaving techniques involved.",
                     "in a way that reduces waste without sacrificing fit.",
                     "balancing formality with genuine comfort."],
        "questions_b": [
            "Do you have this in a larger size?",
            "How much is this shirt?",
            "Can I try this on?",
            "What should I wear tomorrow?",
            "Where is the fitting room?",
            "Does this colour suit me?",
        ],
        "questions_i": [
            "Is this outfit appropriate for a job interview?",
            "Can this be altered before Friday?",
            "What fabric is best for hot and humid weather?",
            "How do I keep this from shrinking in the wash?",
            "Do you offer exchanges if the size is wrong?",
        ],
        "questions_a": [
            "How has fast fashion reshaped local garment industries?",
            "What distinguishes genuine craftsmanship from mass production in tailoring?",
            "Can traditional textiles stay commercially viable without losing authenticity?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "jobs_careers": {
        "subjects": [
            "The applicant", "My supervisor", "A fresh graduate", "The recruiter",
            "The night-shift nurse", "Our team lead", "The delivery rider",
            "A freelance designer", "The store manager", "The engineer",
            "The call centre agent", "The teacher on probation",
        ],
        "verbs_b": ["applied for", "started", "left", "accepted", "learned",
                    "finished", "asked about", "signed"],
        "verbs_i": ["negotiated", "resigned from", "transferred to", "trained for",
                    "took on", "was promoted to", "shortlisted", "declined"],
        "verbs_a": ["strategically pivoted into", "renegotiated the terms of",
                    "restructured", "transitioned into", "benchmarked",
                    "systematically upskilled for"],
        "objects_b": ["a new job", "the night shift", "the contract",
                      "the interview", "a part-time role", "the training",
                      "the schedule"],
        "objects_i": ["a supervisory position", "the overseas assignment",
                      "a career in data analysis", "the probationary review",
                      "an internal transfer", "the performance appraisal"],
        "objects_a": ["a lateral move into product management",
                      "a compensation package reflecting market rates",
                      "an entire career built on incremental specialisation",
                      "the department's long-term succession plan"],
        "extras_b": ["last month.", "after graduation.", "without telling anyone.",
                     "on the first day.", "with some hesitation.", "right away."],
        "extras_i": ["after weighing the pay against the commute.",
                     "despite having no formal experience in the field.",
                     "once the probation period ended.",
                     "because the growth opportunities were clearer.",
                     "with strong support from the whole team."],
        "extras_a": ["having carefully mapped the skills gap in advance.",
                     "with a clear view of where the industry is heading.",
                     "accepting short-term uncertainty for long-term positioning.",
                     "in line with a deliberate five-year career strategy."],
        "questions_b": [
            "What do you do for a living?",
            "Do you like your job?",
            "What time do you start work?",
            "Are they still hiring?",
            "How long have you worked here?",
            "Is it a full-time position?",
        ],
        "questions_i": [
            "What qualifications do I need for this role?",
            "How should I answer questions about salary expectations?",
            "Is there room for growth in this company?",
            "What does a typical day in this job look like?",
            "How soon will I hear back after the interview?",
        ],
        "questions_a": [
            "How do you evaluate a job offer beyond the salary figure?",
            "What obligations does an employer have when restructuring a team?",
            "Is specialisation or versatility more valuable in an unstable job market?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "celebrations": {
        "subjects": [
            "The whole family", "Our neighbours", "The birthday girl",
            "The town", "My titas", "The wedding party", "The organisers",
            "Everyone in the barangay", "The graduating class", "The hosts",
        ],
        "verbs_b": ["celebrated", "decorated", "cooked", "invited", "sang",
                    "danced", "prepared", "gathered for"],
        "verbs_i": ["organised", "hosted", "catered", "coordinated", "livestreamed",
                    "commemorated", "arranged", "budgeted for"],
        "verbs_a": ["choreographed", "curated", "orchestrated",
                    "ceremonially observed", "meticulously planned"],
        "objects_b": ["the birthday party", "the whole house", "a big meal",
                      "the guests", "the cake", "the fiesta", "the reunion"],
        "objects_i": ["the surprise anniversary dinner",
                      "the graduation celebration", "the community fiesta",
                      "the wedding reception", "the Christmas gathering",
                      "the send-off party"],
        "objects_a": ["a three-day festival rooted in local tradition",
                      "an intergenerational family reunion",
                      "a ceremony blending modern and customary elements",
                      "a commemoration honouring the town's founding"],
        "extras_b": ["last Sunday.", "all night.", "with lots of food.",
                     "for the first time.", "very early.", "at the town plaza."],
        "extras_i": ["even though the budget was tight.",
                     "after weeks of quiet preparation.",
                     "so that relatives abroad could join in.",
                     "despite the sudden change in weather.",
                     "with contributions from every household."],
        "extras_a": ["preserving customs that had nearly been forgotten.",
                     "with a programme balancing solemnity and celebration.",
                     "drawing visitors from neighbouring provinces.",
                     "in a way that honoured the elders without excluding the young."],
        "questions_b": [
            "When is the party?",
            "What are we celebrating?",
            "Can I bring something?",
            "Where will the wedding be held?",
            "How many guests are coming?",
            "Is it a formal event?",
        ],
        "questions_i": [
            "What is the customary gift for this kind of celebration?",
            "How early should we send out the invitations?",
            "Is there a dress code for the ceremony?",
            "What food do people usually serve at this festival?",
            "How do families here celebrate the New Year?",
        ],
        "questions_a": [
            "How do communal festivals reinforce social cohesion over generations?",
            "What happens to a tradition when its original meaning is forgotten?",
            "How do families balance tradition with the cost of hosting?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "city_places": {
        "subjects": [
            "The new mall", "Our barangay hall", "The public market",
            "The city government", "The corner store", "The old church",
            "The bus terminal", "A small café near the plaza", "The local clinic",
            "The public library", "The night market",
        ],
        "verbs_b": ["opened", "closed", "moved", "expanded", "renovated",
                    "welcomed", "served", "hosted"],
        "verbs_i": ["relocated", "modernised", "accommodated", "supplied",
                    "connected", "upgraded", "subsidised", "streamlined"],
        "verbs_a": ["revitalised", "repurposed", "master-planned",
                    "pedestrianised", "integrated", "decentralised"],
        "objects_b": ["the whole neighbourhood", "hundreds of customers",
                      "the small shops", "the main road", "the waiting area",
                      "the parking lot", "the old building"],
        "objects_i": ["the surrounding communities", "the daily commuters",
                      "the vendors along the street", "the drainage system",
                      "the public transport routes", "the weekend crowd"],
        "objects_a": ["the entire commercial district",
                      "the city's ageing transport infrastructure",
                      "an underused waterfront area",
                      "the network of informal settlements nearby"],
        "extras_b": ["last year.", "every day.", "since January.",
                     "on weekends.", "at six in the morning.", "for the holidays."],
        "extras_i": ["after months of construction delays.",
                     "in response to growing demand.",
                     "with funding from the local council.",
                     "much faster than residents expected.",
                     "while keeping the original façade intact."],
        "extras_a": ["as part of a broader urban renewal strategy.",
                     "with mixed results for long-time residents.",
                     "prioritising walkability over vehicle throughput.",
                     "after extensive but uneven public consultation."],
        "questions_b": [
            "Is there a pharmacy near here?",
            "What time does the market open?",
            "Where is the nearest ATM?",
            "How do I get to the town hall?",
            "Is this place open on Sundays?",
            "Is there parking nearby?",
        ],
        "questions_i": [
            "Which part of the city is best for families?",
            "How much does it cost to rent around here?",
            "Is this neighbourhood safe to walk in at night?",
            "Where do locals usually eat around this area?",
            "How bad is the traffic during rush hour?",
        ],
        "questions_a": [
            "How does urban density affect access to public services here?",
            "What trade-offs does redevelopment impose on long-term residents?",
            "Can informal markets coexist with formal urban planning?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "gardening_farming": {
        "subjects": [
            "The farmer", "My grandmother", "The farm workers", "My uncle",
            "The cooperative", "The gardener", "Everyone in the household",
            "The tenant farmer", "The agriculture officer", "The harvest crew",
            "My father", "The neighbouring farm",
        ],
        "verbs_b": ["planted", "watered", "harvested", "picked", "grew", "sold",
                    "weeded", "dried"],
        "verbs_i": ["fertilised", "cultivated", "rotated", "transplanted",
                    "pruned", "composted", "irrigated", "stored"],
        "verbs_a": ["intercropped", "soil-tested", "mechanised",
                    "organically certified", "optimised the yield of",
                    "drought-proofed"],
        "objects_b": ["the tomatoes", "the rice", "the mango tree", "the seeds",
                      "the vegetables", "the small plot", "the herbs"],
        "objects_i": ["the second planting season", "the compost heap",
                      "the vegetable beds", "the irrigation lines",
                      "the fruit trees along the fence", "the seedling nursery"],
        "objects_a": ["a diversified cropping system",
                      "the farm's soil fertility programme",
                      "a post-harvest storage facility",
                      "an integrated pest management plan"],
        "extras_b": ["before the rain came.", "every morning.", "by hand.",
                     "at the end of the season.", "with the whole family.",
                     "in the small garden."],
        "extras_i": ["following advice from the agriculture office.",
                     "to make the most of the short dry spell.",
                     "without using any chemical spray.",
                     "after the typhoon damaged the first crop.",
                     "so the soil could recover properly."],
        "extras_a": ["achieving a measurable improvement in yield per hectare.",
                     "while reducing dependence on imported fertiliser.",
                     "with careful attention to long-term soil health.",
                     "in line with climate-resilient farming guidelines."],
        "questions_b": [
            "When is the best time to plant this?",
            "How often should I water these plants?",
            "Do these need full sunlight?",
            "Where can I buy seeds?",
            "Is this fruit ready to pick?",
            "Why are the leaves turning yellow?",
        ],
        "questions_i": [
            "What crops grow well in this kind of soil?",
            "How do I keep pests away without using chemicals?",
            "Is it worth composting kitchen waste at home?",
            "How long before these seedlings can be transplanted?",
            "What is the going price for rice this season?",
        ],
        "questions_a": [
            "How does crop rotation affect long-term soil fertility?",
            "What makes smallholder farming economically viable today?",
            "How are changing rainfall patterns reshaping planting calendars?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "fitness_exercise": {
        "subjects": [
            "The coach", "My gym buddy", "The running group", "A beginner",
            "The physiotherapist", "Our basketball team", "The yoga instructor",
            "The swimmer", "My trainer", "The whole class",
        ],
        "verbs_b": ["ran", "stretched", "lifted", "joined", "practised", "walked",
                    "rested", "warmed up for"],
        "verbs_i": ["scheduled", "increased", "monitored", "adjusted",
                    "recovered from", "sustained", "modified", "tracked"],
        "verbs_a": ["periodised", "progressively overloaded", "rehabilitated",
                    "optimised", "benchmarked", "individualised"],
        "objects_b": ["five kilometres", "the morning workout", "the weights",
                      "a new class", "the warm-up", "the training session",
                      "the whole routine"],
        "objects_i": ["the weekly training plan", "the recovery schedule",
                      "an old knee injury", "the strength programme",
                      "the marathon preparation", "the rest days"],
        "objects_a": ["a twelve-week periodised training block",
                      "the athlete's load management protocol",
                      "a return-to-play progression after injury",
                      "the balance between intensity and recovery"],
        "extras_b": ["before breakfast.", "three times a week.", "very slowly.",
                     "without any equipment.", "at the park.", "after work."],
        "extras_i": ["without aggravating the old injury.",
                     "while still working full-time.",
                     "building up gradually over two months.",
                     "with proper form from the very first session.",
                     "even on days when motivation was low."],
        "extras_a": ["with objective markers rather than perceived effort alone.",
                     "accounting for sleep, nutrition, and accumulated fatigue.",
                     "under supervision until movement quality was consistent.",
                     "in a way that prioritised longevity over short-term gains."],
        "questions_b": [
            "How often do you exercise?",
            "Is this exercise safe for beginners?",
            "Do I need to warm up first?",
            "How much does the gym cost per month?",
            "Can we go running tomorrow?",
            "Is walking enough exercise?",
        ],
        "questions_i": [
            "How long should I rest between sets?",
            "What should I eat before a long run?",
            "Is it normal to feel sore for two days?",
            "How do I avoid injuring my back when lifting?",
            "How many rest days do I actually need each week?",
        ],
        "questions_a": [
            "How does training volume interact with recovery capacity over time?",
            "What evidence supports strength training for injury prevention?",
            "Why do most fitness programmes fail at the adherence stage rather than the design stage?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "culture_traditions": {
        "subjects": [
            "The elders", "The community", "Our grandparents", "The local weavers",
            "The younger generation", "The village", "The storyteller",
            "The cultural group", "The family", "The dance troupe",
        ],
        "verbs_b": ["kept", "taught", "shared", "remembered", "followed",
                    "passed on", "practised", "showed"],
        "verbs_i": ["preserved", "revived", "documented", "adapted", "honoured",
                    "reinterpreted", "transmitted", "safeguarded"],
        "verbs_a": ["contextualised", "codified", "recontextualised",
                    "institutionalised", "archived", "reasserted"],
        "objects_b": ["the old songs", "the family recipe", "the language",
                      "the dance", "the stories", "the customs", "the festival"],
        "objects_i": ["the traditional weaving patterns",
                      "the oral history of the village",
                      "the rituals surrounding harvest season",
                      "the mother tongue at home",
                      "the recipes handed down for generations",
                      "the local dialect"],
        "objects_a": ["an intangible cultural heritage under quiet threat",
                      "a body of oral literature never before transcribed",
                      "ceremonial practices with pre-colonial origins",
                      "the symbolic vocabulary embedded in the textiles"],
        "extras_b": ["for many years.", "to the children.", "every fiesta.",
                     "in their own language.", "with great care.", "at home."],
        "extras_i": ["before the last fluent speakers passed away.",
                     "so that the younger generation would not lose it.",
                     "with support from the local cultural office.",
                     "even as the town modernised around them.",
                     "in a form that made sense to young people."],
        "extras_a": ["without freezing the tradition into a museum piece.",
                     "acknowledging that living cultures necessarily change.",
                     "with the consent and authorship of the community itself.",
                     "resisting the pressure to simplify it for outsiders."],
        "questions_b": [
            "What is this festival for?",
            "Who taught you this song?",
            "Do you still speak your first language at home?",
            "Is this a traditional dish?",
            "What does this symbol mean?",
            "How old is this tradition?",
        ],
        "questions_i": [
            "How do families here pass traditions on to their children?",
            "Why is this custom less common than it used to be?",
            "What does this ceremony represent in your community?",
            "Are young people still learning the traditional crafts?",
            "How has the local dialect changed over the years?",
        ],
        "questions_a": [
            "How does a tradition survive migration and language shift?",
            "Who has the authority to decide what counts as authentic practice?",
            "What is lost when oral traditions are written down?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "business": {
        "subjects": [
            "The small business owner", "Our supplier", "The startup",
            "The sari-sari store", "The online seller", "The franchise",
            "A family business", "The marketing team", "The distributor",
            "The cooperative", "The new competitor",
        ],
        "verbs_b": ["opened", "sold", "ordered", "delivered", "priced",
                    "advertised", "restocked", "packed"],
        "verbs_i": ["expanded", "diversified", "sourced", "negotiated",
                    "invoiced", "outsourced", "rebranded", "forecast"],
        "verbs_a": ["scaled", "restructured", "capitalised", "hedged against",
                    "systematised", "franchised"],
        "objects_b": ["the products", "a new branch", "the daily stock",
                      "the orders", "the shop", "the flyers", "the packaging"],
        "objects_i": ["the delivery arrangement", "the supplier contract",
                      "the online storefront", "the monthly inventory",
                      "the customer loyalty programme", "the pricing structure"],
        "objects_a": ["a multi-channel distribution strategy",
                      "the company's working capital position",
                      "an operating model built for seasonal demand",
                      "the entire supply chain from source to shelf"],
        "extras_b": ["last month.", "at a lower price.", "very quickly.",
                     "on credit.", "before the holidays.", "with a small loan."],
        "extras_i": ["without taking on additional debt.",
                     "after studying what customers actually asked for.",
                     "despite rising transport costs.",
                     "once the first branch became profitable.",
                     "using a simple spreadsheet and a lot of discipline."],
        "extras_a": ["while protecting margins in a price-sensitive market.",
                     "with careful attention to cash flow rather than revenue alone.",
                     "in anticipation of a shift in consumer behaviour.",
                     "balancing growth against the risk of overextension."],
        "questions_b": [
            "How much is this in bulk?",
            "Do you deliver?",
            "Can I pay in instalments?",
            "What time does the shop open?",
            "Do you accept online payment?",
            "Is there a discount for regular customers?",
        ],
        "questions_i": [
            "How much capital do I need to start a small business?",
            "What permits are required to open a shop here?",
            "How do you set prices when costs keep changing?",
            "Is it better to sell online or keep a physical store?",
            "How do you handle customers who never pay on time?",
        ],
        "questions_a": [
            "How should a small business price for resilience rather than volume?",
            "What separates a business that scales from one that merely grows busier?",
            "How much inventory risk is reasonable in a volatile supply market?",
        ],
    },

    # ────────────────────────────────────────────────────────────────────
    "kids_parenting": {
        "subjects": [
            "The toddler", "My youngest child", "The new parents", "The babysitter",
            "The kindergarten teacher", "My nephew", "The children",
            "A first-time mother", "The paediatrician", "The whole playgroup",
        ],
        "verbs_b": ["fed", "carried", "dressed", "played with", "read to",
                    "walked", "calmed", "watched"],
        "verbs_i": ["settled", "encouraged", "supervised", "comforted",
                    "redirected", "praised", "prepared", "enrolled"],
        "verbs_a": ["scaffolded", "co-regulated with", "consistently reinforced",
                    "gently redirected", "modelled patience for"],
        "objects_b": ["the baby", "the little boy", "the bedtime story",
                      "the twins", "the crying child", "the school bag",
                      "the snack"],
        "objects_i": ["the bedtime routine", "the first day of school",
                      "a difficult tantrum", "the screen-time rules",
                      "the picky eating phase", "the sibling arguments"],
        "objects_a": ["the developmental milestones worth watching for",
                      "a consistent approach to discipline across both parents",
                      "the transition from home care to formal schooling",
                      "the child's growing need for autonomy"],
        "extras_b": ["every night.", "very patiently.", "before nap time.",
                     "with a lot of love.", "after school.", "in the afternoon."],
        "extras_i": ["without raising her voice once.",
                     "even after a long and exhausting day.",
                     "using the same routine every single evening.",
                     "while trying not to compare him to his older sister.",
                     "in a way the child could actually understand."],
        "extras_a": ["recognising that consistency matters more than intensity.",
                     "with age-appropriate expectations rather than adult standards.",
                     "allowing room for mistakes without withdrawing support.",
                     "long before the behaviour became a pattern."],
        "questions_b": [
            "How old is your baby?",
            "Is she sleeping through the night yet?",
            "What time do the kids go to bed?",
            "Can he eat this?",
            "Does he go to school already?",
            "Do you need help carrying her?",
        ],
        "questions_i": [
            "How do you handle tantrums in public?",
            "When should a child start school here?",
            "How much screen time is reasonable at this age?",
            "What do you do when siblings keep fighting?",
            "Is it normal for a toddler to be this picky about food?",
        ],
        "questions_a": [
            "How do parenting styles shape long-term emotional regulation?",
            "What developmental signs warrant a professional assessment?",
            "How do parents stay consistent when they fundamentally disagree?",
        ],
    },
}
